version: '3.5'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    tty: true    
    stdin_open: true  
    volumes:
      - ./code:/code
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: cruddb1
      POSTGRES_PASSWORD: secret
    ports:
     - '5555:5433'
    volumes:
     - ./pgdata1:/var/lib/pgsql/12/data  
    command: -p 5433 